### ISSUE TITLE
Cannot find name 'SparkRequests'

### ISSUE THREAD

**Issue by johnsoncodehk** [JEphron/GameSparks-typings#1]
Thank you for this great project.
This project is working good, but missing declaration of SparkRequests.
Can you add the declaration?

Thanks in advance
Johnson

**Comment by JEphron** [comment]
GameSparks used to have a public git repo containing their documentation as .md files, which I parsed to generate these typings. Unfortunately they seem to have taken it down. If you want to hand-write a declaration for SparkRequests and submit a pull request, I'll merge it in for you.

**Comment by johnsoncodehk** [comment]
I will try to parsed the web API from https://docs.gamesparks.com/api-documentation, It's too much content.

**Comment by johnsoncodehk** [comment]
Request API typings: https://github.com/johnsoncodehk/gamesparks-request-api-typings

I set gamesparks-typings and gamesparks-request-api-typings to git sub module in my project, that will easy to maintain.

**Comment by JEphron** [comment]
Nice work!
